# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Push a new release build to the App Store"
  lane :release do
      increment_build_number
      deliver(submit_for_review: true, metadata_path: "./metadata")
      slack(message: "App submitted for review!",channel: "#development")
  end

  desc "Push a new release build to the Test Flight"
  lane :beta do
      increment_build_number
      build_app(workspace: "BirthdayReminder.xcworkspace", scheme: "BirthdayReminder")
      upload_to_testflight(skip_waiting_for_build_processing: true)
      slack(message: "App(beta) successfully released!",channel: "#development")
  end

end
